# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b537e6dbf90c0e1fd3f77c5d817bf8ccf2dcdbf98a9cee5a82ca952ab6011215e01028bb652b1114cddfabfc90af8657db032516e2048cdc45b5cec3c680b8

test:
  secret_key_base: f88ef10f31091dcd6ffa878db8192890d3c2c3fdd67bedec46c3552aa8b3491e1e8d21f8980d6b32970da188b5fe8aae52feb5a5554794d84001121e74253e3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
