guard :rspec, cmd: 'bundle exec rspec --color --format documentation' do
	watch(%r{^spec/.+_soec\.rb$})
	watch(%r{^models/(.+)\.rb$}) { |m| "spec/#{m[1]}_spec.rb" }
	watch("app.rb") { |m| "spec/app_spec.rb"}
end